### ISSUE TITLE
Padding missing in OF 1.0 PacketIn message

### ISSUE THREAD

**Issue by maufl** [jonstout/ogo#37]
The [PacketIn](https://github.com/jonstout/ogo/blob/master/protocol/ofp10/ofp10.go#L177) struct does not include the padding, which is not necessary but also does not consider the padding when (un-)marshaling the packet, which leads to wrong packets.

As far as I can see this repo is not really maintained anymore. Should I send a pull request anyway or fork it? (I have another issue, MessageStream taking a net.TCPConn instead of a net.Conn and might have more issues in the future)

**Comment by jonstout** [comment]
@maufl Feel free to open a pull request; I would merge anything you have. If you'll be suggesting or creating many changes I would be willing to add you as a collaborator.
